config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :films
  resources :species
  resources :planets

  root 'films#index'
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_and_belongs_to_many :films
  has_many :characters
  has_many :species

  validates :name, presence: true
  validates :diameter, :rotation_period, :orbital_period, :population, :surface_water, numericality: true
  before_destroy :set_planet_to_unkown

  def set_planet_to_unkown
    unknown_planet_id = Planet.find_by(name: "unknown").id
    self.characters.update_all(planet_id: unknown_planet_id)
    self.species.update_all(planet_id: unknown_planet_id)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @planets = Planet.all.order(:name)
  end

  def show
  end

  def new
    @planet = Planet.new
    respond_modal_with @film
  end

  def edit
    respond_modal_with @film
  end

  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        flash[:success] = "La planète a bien été crée"
        format.html { redirect_to @planet }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @planet.update(planet_params)
        flash[:success] = "La planète a bien été mis à jour"
        format.html { redirect_to @planet }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @planet.destroy
    respond_to do |format|
      flash[:success] = "La planète a bien été supprimé"
      format.html { redirect_to planets_url }
      format.json { head :no_content }
    end
  end

  private
    def set_planet
      @planet = Planet.find(params[:id])
    end

    def planet_params
      planet_params = params.require(:planet).permit(:name, :diameter, :rotation_period, :orbital_period, :gravity, :population, :climate, :terrain, :surface_water)
      planet_params[:characters] = build_characters(params[:planet][:characters]) if params[:planet][:characters]
      planet_params[:films] = build_films(params[:planet][:films]) if params[:planet][:films]
      planet_params[:species] = build_species(params[:planet][:species]) if params[:planet][:species]
      planet_params
    end

    def build_characters(characters)
      characters = characters - [""]
      characters.collect {|character| Character.find(character)}
    end

    def build_films(films)
      films = films - [""]
      films.collect {|film| Film.find(film)}
    end

    def build_species(species)
      species = species - [""]
      species.collect {|specie| Specie.find(specie)}
    end
end

app/helpers/planets_helper.rb
module PlanetsHelper
  def planet_select(current_planet)
    planet_name = current_planet ? current_planet.name : ""
    out = Planet.all.order(:name).collect { |planet| [planet.name, planet.id, selected: planet_name == planet.name] }
  end

  def multiple_planets(planets)
    out = Planet.all.order(:name).collect { |planet| [planet.name, planet.id, selected: (planets.find {|linked| linked.name == planet.name}) ? true : false] }
  end
end

app/views/planets/_form.html.slim
= javascript_pack_tag 'planets/form', 'data-turbolinks-track': 'reload'

- if @planet.errors.any?
  #error_explanation
    h5 = "#{pluralize(@planet.errors.count, "erreur")} détecté:"
    ul
      - @planet.errors.full_messages.each do |message|
        li = message

.input-container.row.align-items-center
  .col-3
    = f.label :name
  .col-9
    = f.text_field :name, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :diameter
  .col-9
    = f.text_field :diameter, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :rotation_period
  .col-9
    = f.text_field :rotation_period, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :orbital_period
  .col-9
    = f.text_field :orbital_period, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :gravity
  .col-9
    = f.text_field :gravity, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :population
  .col-9
    = f.text_field :population, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :climate
  .col-9
    = f.text_field :climate, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :terrain
  .col-9
    = f.text_field :terrain, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :surface_water
  .col-9
    = f.text_field :surface_water, class:'form-control'
    
.input-container.row.align-items-center
  .col-3
    = f.label :characters
  .col-9
    = f.select :characters, options_for_select(multiple_characters(f.object.characters)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

.input-container.row.align-items-center
  .col-3
    = f.label :films
  .col-9
    = f.select :films, options_for_select(multiple_films(f.object.films)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

.input-container.row.align-items-center
  .col-3
    = f.label :species
  .col-9
    = f.select :species, options_for_select(multiple_species(f.object.species)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

app/views/planets/edit.html.slim
= form_for @planet, remote: true, html: {class: 'form-control', data: {modal: true}} do |f|
  = render partial: 'form', locals: {f: f}
  .row.justify-content-center = f.submit "Modifier la planète", class: "btn btn-info"

app/views/planets/index.html.slim
h1 Liste des planètes

table class="table table-hover"
  = link_to new_planet_path, data: {modal: true}, title: 'Ajouter une planète', class: 'icon-btn-add row justify-content-center align-items-center' do 
    i.fa.fa-plus

  thead
    tr
      th Nom
      th.d-none.d-sm-table-cell Diametre
      th.d-none.d-md-table-cell Espèce(s)
      th.d-none.d-xl-table-cell Population
      th.d-none.d-xl-table-cell Film(s)
      th

  tbody
    - @planets.each do |planet|
      tr data-path="#{edit_planet_path(planet)}"
        td= planet.name
        td.d-none.d-sm-table-cell= planet.diameter
        td.d-none.d-md-table-cell= inline_species(planet.species)
        td.d-none.d-xl-table-cell= planet.population
        td.d-none.d-xl-table-cell= inline_films(planet.films)
        td 
          = link_to planet, class: 'icon-table-btn', title: 'Voir' do
            i.fa.fa-eye
          = link_to edit_planet_path(planet), data: {modal: true}, class: 'icon-table-btn', title: 'Modifier' do
            i.fa.fa-edit
          = link_to planet, data: { confirm: 'Are you sure?' }, method: :delete, class: 'icon-table-btn', title: 'Supprimer' do
            i.fa.fa-trash

app/views/planets/new.html.slim
= form_for @planet, remote: true, html: {class: 'form-control', data: {modal: true}} do |f|
  = render partial: 'form', locals: {f: f}
  .row.justify-content-center = f.submit "Créer la planète", class: "btn btn-info"

app/views/planets/show.html.slim
.star-wars-card style="background-image: url(#{asset_pack_path('images/galaxy.jpg')})"
  .row.align-items-start
    .col-xs-12.col-md-6
      .planet
        .wrap
          .background style="background-image: url(#{asset_pack_path('images/planet.jpg')})"
          .clouds style="background-image: url(#{asset_pack_path('images/clouds.png')})"
        .mask

    .col-xs-12.col-md-6
      p= "La planète #{@planet.name} à un diamètre de #{@planet.diameter}km avec une gravité de #{@planet.gravity}. Sa période de rotation est de #{@planet.rotation_period} jours et sa période de révolution est de #{@planet.orbital_period} jours."

      p= "Sa population est de #{@planet.population} habitants. Elle est composé de #{@planet.surface_water}% d'eau à sa surface. Son climat est de type #{@planet.climate} et son sol de type #{@planet.terrain}."

      .row.justify-content-around
        = link_to "Modifier", edit_planet_path(@planet), data: {modal: true}, class: 'btn btn-sw btn-lg'
        = link_to "Supprimer", @planet, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sw btn-lg'

.row.align-items-start
  .col-xs-12.col-md-6.col-xl-4
    h4 Films
    .list-group
      - @planet.films.order(:title).each do |film|
        =link_to film.title, film, class: "list-group-item list-group-item-action"

  .col-xs-12.col-md-6.col-xl-4
    h4 Personnages
    .list-group
      - @planet.characters.order(:name).each do |character|
        =link_to character.name, character, data: {modal: true}, class: "list-group-item list-group-item-action"
  
  .col-xs-12.col-md-6.col-xl-4
    h4 Espèces
    .list-group
      - @planet.species.order(:name).each do |specie|
        =link_to specie.name, specie, data: {modal: true}, class: "list-group-item list-group-item-action"