config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :films
  resources :species
  resources :planets

  root 'films#index'
end

app/models/film.rb
class Film < ApplicationRecord
  has_and_belongs_to_many :characters
  has_and_belongs_to_many :planets
  has_many :species, -> { distinct }, through: :characters

  validates :episode_id, numericality: true
  validates :title, :opening_crawl, :release_date, presence: true
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @films = Film.all.order(:episode_id)
  end

  def show
  end

  def new
    @film = Film.new
    respond_modal_with @film
  end

  def edit
    respond_modal_with @film
  end

  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        flash[:success] = "Le film a bien été crée"
        format.html { redirect_to @film}
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @film.update(film_params)
        flash[:success] = "Le film a bien été mis à jour"
        format.html { redirect_to @film }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @film.destroy
    respond_to do |format|
      flash[:success] = "Le film a bien été supprimé"
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  private
    def set_film
      @film = Film.find(params[:id])
    end

    def film_params
      film_params = params.require(:film).permit(:title, :episode_id, :opening_crawl, :director, :producer, :release_date)
      film_params[:characters] = build_characters(params[:film][:characters]) if params[:film][:characters]
      film_params[:planets] = build_planets(params[:film][:planets]) if params[:film][:planets]
      film_params
    end

    def build_characters(characters)
      characters = characters - [""]
      characters.collect {|character| Character.find(character)}
    end

    def build_planets(planets)
      planets = planets - [""]
      planets.collect {|planet| Planet.find(planet)}
    end
end

app/helpers/films_helper.rb
module FilmsHelper
  def inline_films(films)
    (films.collect {|film| film.title}).join(', ')
  end

  def multiple_films(films)
    out = Film.all.order(:episode_id).collect { |film| ["Episode #{film.episode_id} - #{film.title}", film.id, selected: (films.find {|linked| linked.title == film.title}) ? true : false] }
  end
end

app/views/films/_form.html.slim
= javascript_pack_tag 'films/form', 'data-turbolinks-track': 'reload'

- if @film.errors.any?
  #error_explanation
    h5 = "#{pluralize(@film.errors.count, "erreur")} détecté:"
    ul
      - @film.errors.full_messages.each do |message|
        li = message

.input-container.row.align-items-center
  .col-3
    = f.label :title
  .col-9
    = f.text_field :title, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :episode_id
  .col-9
    = f.text_field :episode_id, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :director
  .col-9
    = f.text_field :director, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :release_date
  .col-9
    = f.text_field :release_date, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :planets
  .col-9
    = f.select :planets, options_for_select(multiple_planets(f.object.planets)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

.input-container.row.align-items-center
  .col-3
    = f.label :characters
  .col-9
    = f.select :characters, options_for_select(multiple_characters(f.object.characters)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

.input-container.row.align-items-start
  .col-3
    = f.label :opening_crawl
  .col-9
    = f.text_area :opening_crawl, class:'form-control', rows: "10"

app/views/films/edit.html.slim
= form_for @film, remote: true, html: {class: 'form-control', data: {modal: true}} do |f|
  = render partial: 'form', locals: {f: f}
  .row.justify-content-center = f.submit "Modifier le film", class: "btn btn-info"

app/views/films/index.html.slim
h1 Liste des films

table class="table table-hover"
  = link_to new_film_path, data: {modal: true}, title: 'Ajouter un film', class: 'icon-btn-add row justify-content-center align-items-center' do 
    i.fa.fa-plus

  thead
    tr
      th.d-none.d-sm-table-cell Episode
      th Titre
      th.d-none.d-md-table-cell Date de sortie
      th.d-none.d-xl-table-cell Producteur
      th

  tbody
    - @films.each do |film|
      tr data-path="#{edit_film_path(film)}"
        td.d-none.d-sm-table-cell= film.episode_id
        td= film.title
        td.d-none.d-md-table-cell= film.release_date
        td.d-none.d-xl-table-cell= film.producer
        td 
          = link_to film, class: 'icon-table-btn', title: 'Voir' do
            i.fa.fa-eye
          = link_to edit_film_path(film), data: {modal: true}, class: 'icon-table-btn', title: 'Modifier' do
            i.fa.fa-edit
          = link_to film, data: { confirm: 'Are you sure?' }, method: :delete, class: 'icon-table-btn', title: 'Supprimer' do
            i.fa.fa-trash

app/views/films/new.html.slim
= form_for @film, remote: true, html: {class: 'form-control', data: {modal: true}} do |f|
  = render partial: 'form', locals: {f: f}
  .row.justify-content-center = f.submit "Créer le film", class: "btn btn-info"

app/views/films/show.html.slim
.star-wars-card style="background-image: url(#{asset_pack_path('images/galaxy.jpg')})"
  .row.align-items-center
    .col-xs-12.col-md-6
      = image_tag asset_pack_path('images/star_wars.png')
      h2 = "Épisode #{@film.episode_id} - #{@film.title.upcase}"
      h4 = "Réalisé par #{@film.director}"
      h4 = "Produit par #{@film.producer}"
      h4 = "Sortie le #{l(@film.release_date, format: :long)}"

    .col-xs-12.col-md-6
      p = @film.opening_crawl

      .row.justify-content-around
        = link_to "Modifier", edit_film_path(@film), data: {modal: true}, class: 'btn btn-sw btn-lg'
        = link_to "Supprimer", @film, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sw btn-lg'

.row.align-items-start
  .col-xs-12.col-md-6.col-xl-4
    h4 Planètes
    .list-group
      - @film.planets.order(:name).each do |planet|
        =link_to planet.name, planet, class: "list-group-item list-group-item-action"

  .col-xs-12.col-md-6.col-xl-4
    h4 Personnages
    .list-group
      - @film.characters.order(:name).each do |character|
        =link_to character.name, character, data: {modal: true}, class: "list-group-item list-group-item-action"
  
  .col-xs-12.col-md-6.col-xl-4
    h4 Espèces
    .list-group
      - @film.species.order(:name).each do |specie|
        =link_to specie.name, specie, data: {modal: true}, class: "list-group-item list-group-item-action"