config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :films
  resources :species
  resources :planets

  root 'films#index'
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :planet
  has_and_belongs_to_many :species
  has_and_belongs_to_many :films

  validates :mass, :height, numericality: true
  validates :name, :planet, presence: true
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    @characters = Character.all.order(:name)
  end

  def show
    respond_modal_with @character
  end

  def new
    @character = Character.new
    respond_modal_with @character
  end

  def edit
    respond_modal_with @character
  end

  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        flash[:success] = "Le personnage a bien été crée"
        format.html { redirect_to characters_url }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @character.update(character_params)
        flash[:success] = "Le personnage a bien été mis à jour"
        format.html { redirect_to characters_url }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @character.destroy
    respond_to do |format|
        flash[:success] = "Le personnage a bien été supprimé"
        format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  private
    def set_character
      @character = Character.find(params[:id])
    end

    def character_params
      character_params = params.require(:character).permit(:name, :birth_year, :eye_color, :gener, :hair_color, :height, :skin_color, :mass)
      character_params[:planet] = Planet.find(params[:character][:planet]) if params[:character][:planet]
      character_params[:films] = build_films(params[:character][:films]) if params[:character][:films]
      character_params[:species] = build_species(params[:character][:species]) if params[:character][:species]
      character_params
    end

    def build_films(films)
      films = films - [""]
      films.collect {|film| Film.find(film)}
    end

    def build_species(species)
      species = species - [""]
      species.collect {|specie| Specie.find(specie)}
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def multiple_characters(characters)
    out = Character.all.order(:name).collect { |character| [character.name, character.id, selected: (characters.find {|linked| linked.name == character.name}) ? true : false] }
  end
end

app/views/characters/_form.html.slim
= javascript_pack_tag 'characters/form', 'data-turbolinks-track': 'reload'

- if @character.errors.any?
  #error_explanation
    h5 = "#{pluralize(@character.errors.count, "erreur")} détecté:"
    ul
      - @character.errors.full_messages.each do |message|
        li = message

.input-container.row.align-items-center
  .col-3
    = f.label :name
  .col-9
    = f.text_field :name, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :gender
  .col-9
    = f.text_field :gender, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :birth_year
  .col-9
    = f.text_field :birth_year, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :eye_color
  .col-9
    = f.text_field :eye_color, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :hair_color
  .col-9
    = f.text_field :hair_color, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :skin_color
  .col-9
    = f.text_field :skin_color, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :mass
  .col-9
    = f.text_field :mass, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :height
  .col-9
    = f.text_field :height, class:'form-control'

.input-container.row.align-items-center
  .col-3
    = f.label :planet
  .col-9
    = f.select :planet, options_for_select(planet_select(f.object.planet)), {}, {class: 'form-control'}
    
.input-container.row.align-items-center
  .col-3
    = f.label :films
  .col-9
    = f.select :films, options_for_select(multiple_films(f.object.films)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

.input-container.row.align-items-center
  .col-3
    = f.label :species
  .col-9
    = f.select :species, options_for_select(multiple_species(f.object.species)), {}, {class: 'selectpicker form-control', multiple: "multiple"}

app/views/characters/edit.html.slim
= form_for @character, remote: true, html: {class: 'form-control', data: {modal: true}} do |f|
  = render partial: 'form', locals: {f: f}
  .row.justify-content-center = f.submit "Modifier le personnage", class: "btn btn-info"

app/views/characters/index.html.slim
h1 Liste des personnages

table class="table table-hover"
  = link_to new_character_path, data: {modal: true}, title: 'Ajouter un personnage', class: 'icon-btn-add row justify-content-center align-items-center' do 
    i.fa.fa-plus

  thead
    tr
      th Nom
      th.d-none.d-sm-table-cell Espèce(s)
      th.d-none.d-md-table-cell Planète
      th.d-none.d-xl-table-cell Film(s)
      th

  tbody
    - @characters.each do |character|
      tr data-path="#{edit_character_path(character)}"
        td= character.name
        td.d-none.d-sm-table-cell= inline_species(character.species)
        td.d-none.d-md-table-cell= character.planet.name
        td.d-none.d-xl-table-cell= inline_films(character.films)
        td 
          = link_to character, data: {modal: true}, class: 'icon-table-btn', title: 'Voir' do
            i.fa.fa-eye
          = link_to edit_character_path(character), data: {modal: true}, class: 'icon-table-btn', title: 'Modifier' do
            i.fa.fa-edit
          = link_to character, data: { confirm: 'Are you sure?' }, method: :delete, class: 'icon-table-btn', title: 'Supprimer' do
            i.fa.fa-trash

app/views/characters/new.html.slim
= form_for @character, remote: true, html: {class: 'form-control', data: {modal: true}} do |f|
  = render partial: 'form', locals: {f: f}
  .row.justify-content-center = f.submit "Créer le personnage", class: "btn btn-info"

app/views/characters/show.html.slim
.show-in-modal
  p= "#{@character.name} est née en #{@character.birth_year} et est originaire de la planète #{@character.planet.name}. Ses cheveux sont de couleur #{@character.hair_color}, sa peau #{@character.skin_color} et ses yeux #{@character.eye_color}. Il mesure #{@character.height}cm et pèse #{@character.mass}kg. Il fait parti de la race des #{inline_species(@character.species)}."

  p= "On a pu apercevoir ce personnage dans #{inline_films(@character.films)}."