config/routes.rb
Rails.application.routes.draw do
  resources :characters
  resources :films
  resources :species
  resources :planets

  root 'films#index'
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title HfaTest
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application'

  body
    - flash.each do |key, value|
      .alert class="alert-#{key}" role="alert"
        = value
    #modal-container

    .row.menu-btn.justify-content-center.align-items-center.d-lg-none
      <i class="fa fa-bars"></i>


    .sidenav.col-xs-12.col-lg-3.col-xl-2.d-lg-block
      .row.menu-close-btn.justify-content-center.align-items-center.d-lg-none
        <i class="fa fa-close"></i>
      .brand
        = image_tag asset_pack_path('images/logo.png')
      = link_to "Films", films_path, class: "link #{'current-path' if controller.controller_name == 'films'}"
      = link_to "Personnages", characters_path, class: "link #{'current-path' if controller.controller_name == 'characters'}"
      = link_to "Planètes", planets_path, class: "link #{'current-path' if controller.controller_name == 'planets'}"
      = link_to "Espèces", species_path, class: "link #{'current-path' if controller.controller_name == 'species'}"

  .container-fluid class="#{controller.controller_name}"
    .col-xs-12.col-lg-9.col-xl-10.offset-lg-3.offset-xl-2
      = yield

app/views/layouts/modal.html.slim
.modal.fade#mainModal tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="mainModalLabel"
  .modal-dialog role="document"
    .modal-content
      button type="button" class="close" data-dismiss="modal"
        span aria-hidden="true"
          |&times;
      = yield